version: "3"

services:
  portfolio-website:
    container_name: portfolio-website
    image: node:14
    build: .
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - /var/portfolio-website/public.pem:/portfolio-website/public.pem
      - /var/portfolio-website/private.key:/portfolio-website/private.key